### ISSUE TITLE
LoadError: ArgumentError: Package FixedPointNumbers Not Installed

### ISSUE THREAD

**Issue by arumugamav** [randyzwitch/ECharts.jl#68] opened 2019-02-23 13:53 UTC
While using ECharts throws Error as follows:
 
julia> using ECharts
[ Info: Precompiling ECharts [top-level]
ERROR: LoadError: ArgumentError: Package FixedPointNumbers [53c48c17-4a7d-5ca2-90c5-79b7896eea93] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

**Environment:**
CentOS7.4 64bit

**Julia Version:**
julia-1.1.0

**Dependend Packages Installed:**
FixedPointNumbers
Colors
NoveltyColors
ColorBrewer
Parameters
OrderedCollections
JSON

**Comment by randyzwitch** [comment] 2019-02-23 14:19
I wonder if this is a Centos issue...just installed on Ubuntu 18.10 and it seemed to add FixedPointNumbers (I don't even know what FixedPointNumbers is, which is why its not a hard dependency):

```julia
(v1.1) pkg> add ECharts
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Widgets ───────── v0.5.0
 Installed Conda ─────────── v1.2.0
 Installed DiffRules ─────── v0.0.10
 Installed MacroTools ────── v0.4.5
 Installed WebSockets ────── v1.3.0
 Installed ForwardDiff ───── v0.10.3
 Installed Blink ─────────── v0.10.0
 Installed DiffResults ───── v0.0.4
 Installed OffsetArrays ──── v0.10.0
 Installed Mux ───────────── v0.6.0
 Installed Distances ─────── v0.8.0
 Installed StatsFuns ─────── v0.8.0
 Installed DiffEqDiffTools ─ v0.8.0
 Installed NLSolversBase ─── v7.3.1
 Installed Interpolations ── v0.11.2
 Installed Mustache ──────── v0.5.11
 Installed WeakRefStrings ── v0.5.7
  Updating `~/.julia/environments/v1.1/Project.toml`
  [f9630f5b] + ECharts v0.1.1
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [621f4979] + AbstractFFTs v0.3.2
  [7d9fca2a] + Arpack v0.3.0
  [13072b0f] + AxisAlgorithms v0.3.0
  [ad839575] + Blink v0.10.0
  [49dc2e85] + Calculus v0.4.1
  [a2cac450] + ColorBrewer v0.4.0
  [3da002f7] + ColorTypes v0.7.5
  [5ae59095] + Colors v0.9.5
  [bbf7d656] + CommonSubexpressions v0.2.0
  [8f4d0f93] + Conda v1.2.0
  [01453d9d] + DiffEqDiffTools v0.8.0
  [163ba53b] + DiffResults v0.0.4
  [b552c78f] + DiffRules v0.0.10
  [b4f34e82] ↑ Distances v0.7.4 ⇒ v0.8.0
  [31c24e10] + Distributions v0.16.4
  [f9630f5b] + ECharts v0.1.1
  [7a1cc6ca] + FFTW v0.2.4
  [53c48c17] + FixedPointNumbers v0.5.3
  [f6369f11] + ForwardDiff v0.10.3
  [a98d9a8b] + Interpolations v0.11.2
  [97c1335a] + JSExpr v0.5.0
  [5ab0869b] + KernelDensity v0.5.1
  [d3d80556] + LineSearches v7.0.1
  [1914dd2f] ↑ MacroTools v0.4.4 ⇒ v0.4.5
  [ffc61752] + Mustache v0.5.11
  [a975b10e] + Mux v0.6.0
  [d41bc354] + NLSolversBase v7.3.1
  [77ba4419] + NaNMath v0.3.2
  [8f4894fe] + NoveltyColors v0.4.0
  [6fe1bfb0] + OffsetArrays v0.10.0
  [429524aa] + Optim v0.17.2
  [90014a1f] + PDMats v0.9.6
  [d96e819e] + Parameters v0.10.3
  [85a6dd25] + PositiveFactorizations v0.2.1
  [1fd47b50] + QuadGK v2.0.3
  [c84ed2f1] + Ratios v0.3.0
  [79098fc4] + Rmath v0.5.0
  [90137ffa] + StaticArrays v0.10.2
  [4c63d2b9] + StatsFuns v0.8.0
  [81def892] + VersionParsing v1.1.3
  [ea10d353] ↑ WeakRefStrings v0.5.5 ⇒ v0.5.7
  [104b5d7c] ↑ WebSockets v1.2.0 ⇒ v1.3.0
  [cc8bc4a8] ↑ Widgets v0.4.4 ⇒ v0.5.0
  [efce3f68] + WoodburyMatrices v0.4.1
  [4607b0f0] + SuiteSparse 
  Building Blink → `~/.julia/packages/Blink/rdBVQ/deps/build.log`
  Building Conda → `~/.julia/packages/Conda/CpuvI/deps/build.log`

julia> using ECharts
[ Info: Precompiling ECharts [f9630f5b-a116-5b0c-bd6c-4699aee17694]
WARNING: could not import Base.quit into AtomShell
```

![screenshot from 2019-02-23 09-18-34](https://user-images.githubusercontent.com/2762787/53287568-07d5b900-374c-11e9-92a3-d778d454eba8.png)

**Comment by randyzwitch** [comment] 2019-02-24 16:01
Looks like it works for OSX Mojave as well, so this looks like it points to a CentOS issue or a local environment issue.

Would you be willing to start from a clean environment and try again? Or maybe just start with a `] update`? It could be that one of the actual ECharts dependencies did something with FixedPointNumbers and you just need to pull that updated package in.

**Comment by randyzwitch** [comment] 2019-03-22 18:46
Closing for now as I can't reproduce on Ubuntu or OSX, if this is still an issue let me know

**Closed by randyzwitch** 2019-03-22 18:46 UTC
